backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Post"
    label_plural: "Posts"
    name: "post"
    folder: "src/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Organization, name: organization, widget: string }
      - label: "Main Menu"
        name: "main_menu"
        file: "src/_data/main_menu.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }