backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter

media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:

  - label: "Page"
    label_plural: "Pages"
    name: "pages"
    folder: "src/pages"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "markdown", required: false, minimal: true, buttons: ['link'] }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false, hint: "Tag with 'pathways' to use as pathway. Pathways automatically show up anywhere pathways are mentioned (hero form, the [Become a Teacher](/become-a-teacher/) page, etc." }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        collapsed: true
        hint: "Influences sidebar navigation. Uses the [eleventy-navigation](https://www.11ty.dev/docs/plugins/navigation/) plugin."
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Key", name: "key", widget: "string", hint: "This is a machine-name for this page. This should be unique, lowercase, no-spaces (use - or _ ), and never change (do not edit once set)." }
          - { 
            label: "Parent", 
            name: "parent", 
            required: false,
            widget: "relation", 
            collection: "pages",
            search_fields: ["title"],
            value_field: "eleventyNavigation.key",
            display_fields: ["{{title}} [{{eleventyNavigation.key}}]"]
          }
          - { label: "Order", name: "order", widget: "number", default: 0, value_type: "int" }
      - label: "Metadata"
        name: "meta"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Description", name: "description", widget: "text", required: false, hint: "This description is most often used beneath search results and when this page is shown on social networks." }

  - label: "Quote"
    label_plural: "Quotes"
    name: "quote"
    folder: "src/quotes"
    create: true
    choose_url: false
    sortable_fields: ['title', 'cardinality']
    summary: "{{title}} (Cardinality: {{fields.cardinality | default('0')}})"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Quote", name: "quote", widget: "text", hint: "Please do not wrap this field in quotation marks. This is added automatically." }
      - { label: "Portrait", name: "portrait", widget: "image", required: false }
      - { label: "Cardinality", name: "cardinality", widget: "number", default: 0}

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Organization, name: organization, widget: string }
      - label: "Main Menu"
        name: "main_menu"
        file: "src/_data/main_menu.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }